/****** Object:  Table [dbo].[Country]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [Country] ON
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (1, N'AFGHANISTAN', N'AF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (2, N'LAND ISLANDS', N'AX', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (3, N'ALBANIA', N'AL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (4, N'ALGERIA', N'DZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (5, N'AMERICAN SAMOA', N'AS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (6, N'ANDORRA', N'AD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (7, N'ANGOLA', N'AO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (8, N'ANGUILLA', N'AI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (9, N'ANTARCTICA', N'AQ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (10, N'ANTIGUA AND BARBUDA', N'AG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (11, N'ARGENTINA', N'AR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (12, N'ARMENIA', N'AM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (13, N'ARUBA', N'AW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (14, N'AUSTRALIA', N'AU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (15, N'AUSTRIA', N'AT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (16, N'AZERBAIJAN', N'AZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (17, N'BAHAMAS', N'BS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (18, N'BAHRAIN', N'BH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (19, N'BANGLADESH', N'BD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (20, N'BARBADOS', N'BB', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (21, N'BELARUS', N'BY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (22, N'BELGIUM', N'BE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (23, N'BELIZE', N'BZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (24, N'BENIN', N'BJ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (25, N'BERMUDA', N'BM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (26, N'BHUTAN', N'BT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (27, N'BOLIVIA', N'BO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (28, N'BOSNIA AND HERZEGOVINA', N'BA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (29, N'BOTSWANA', N'BW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (30, N'BOUVET ISLAND', N'BV', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (31, N'BRAZIL', N'BR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (32, N'BRITISH INDIAN OCEAN TERRITORY', N'IO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (33, N'BRUNEI DARUSSALAM', N'BN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (34, N'BULGARIA', N'BG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (35, N'BURKINA FASO', N'BF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (36, N'BURUNDI', N'BI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (37, N'CAMBODIA', N'KH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (38, N'CAMEROON', N'CM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (39, N'CANADA', N'CA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (40, N'CAPE VERDE', N'CV', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (41, N'CAYMAN ISLANDS', N'KY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (42, N'CENTRAL AFRICAN REPUBLIC', N'CF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (43, N'CHAD', N'TD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (44, N'CHILE', N'CL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (45, N'CHINA', N'CN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (46, N'CHRISTMAS ISLAND', N'CX', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (47, N'COCOS (KEELING) ISLANDS', N'CC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (48, N'COLOMBIA', N'CO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (49, N'COMOROS', N'KM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (50, N'CONGO', N'CG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (51, N'CONGO, THE DEMOCRATIC REPUBLIC OF THE', N'CD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (52, N'COOK ISLANDS', N'CK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (53, N'COSTA RICA', N'CR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (54, N'COTE D''IVOIRE', N'CI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (55, N'CROATIA', N'HR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (56, N'CUBA', N'CU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (57, N'CYPRUS', N'CY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (58, N'CZECH REPUBLIC', N'CZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (59, N'DENMARK', N'DK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (60, N'DJIBOUTI', N'DJ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (61, N'DOMINICA', N'DM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (62, N'DOMINICAN REPUBLIC', N'DO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (63, N'ECUADOR', N'EC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (64, N'EGYPT', N'EG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (65, N'EL SALVADOR', N'SV', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (66, N'EQUATORIAL GUINEA', N'GQ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (67, N'ERITREA', N'ER', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (68, N'ESTONIA', N'EE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (69, N'ETHIOPIA', N'ET', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (70, N'FALKLAND ISLANDS (MALVINAS)', N'FK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (71, N'FAROE ISLANDS', N'FO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (72, N'FIJI', N'FJ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (73, N'FINLAND', N'FI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (74, N'FRANCE', N'FR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (75, N'FRENCH GUIANA', N'GF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (76, N'FRENCH POLYNESIA', N'PF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (77, N'FRENCH SOUTHERN TERRITORIES', N'TF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (78, N'GABON', N'GA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (79, N'GAMBIA', N'GM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (80, N'GEORGIA', N'GE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (81, N'GERMANY', N'DE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (82, N'GHANA', N'GH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (83, N'GIBRALTAR', N'GI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (84, N'GREECE', N'GR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (85, N'GREENLAND', N'GL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (86, N'GRENADA', N'GD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (87, N'GUADELOUPE', N'GP', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (88, N'GUAM', N'GU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (89, N'GUATEMALA', N'GT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (90, N'GUERNSEY', N'GG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (91, N'GUINEA', N'GN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (92, N'GUINEA-BISSAU', N'GW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (93, N'GUYANA', N'GY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (94, N'HAITI', N'HT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (95, N'HEARD ISLAND AND MCDONALD ISLANDS', N'HM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (96, N'HOLY SEE (VATICAN CITY STATE)', N'VA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (97, N'HONDURAS', N'HN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (98, N'HONG KONG', N'HK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (99, N'HUNGARY', N'HU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (100, N'ICELAND', N'IS', 1)
GO
print 'Processed 100 total records'
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (101, N'INDIA', N'IN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (102, N'INDONESIA', N'ID', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (103, N'IRAN, ISLAMIC REPUBLIC OF', N'IR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (104, N'IRAQ', N'IQ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (105, N'IRELAND', N'IE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (106, N'ISLE OF MAN', N'IM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (107, N'ISRAEL', N'IL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (108, N'ITALY', N'IT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (109, N'JAMAICA', N'JM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (110, N'JAPAN', N'JP', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (111, N'JERSEY', N'JE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (112, N'JORDAN', N'JO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (113, N'KAZAKHSTAN', N'KZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (114, N'KENYA', N'KE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (115, N'KIRIBATI', N'KI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (116, N'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', N'KP', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (117, N'KOREA, REPUBLIC OF', N'KR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (118, N'KUWAIT', N'KW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (119, N'KYRGYZSTAN', N'KG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (120, N'LAO PEOPLE''S DEMOCRATIC REPUBLIC', N'LA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (121, N'LATVIA', N'LV', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (122, N'LEBANON', N'LB', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (123, N'LESOTHO', N'LS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (124, N'LIBERIA', N'LR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (125, N'LIBYAN ARAB JAMAHIRIYA', N'LY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (126, N'LIECHTENSTEIN', N'LI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (127, N'LITHUANIA', N'LT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (128, N'LUXEMBOURG', N'LU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (129, N'MACAO', N'MO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (130, N'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', N'MK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (131, N'MADAGASCAR', N'MG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (132, N'MALAWI', N'MW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (133, N'MALAYSIA', N'MY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (134, N'MALDIVES', N'MV', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (135, N'MALI', N'ML', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (136, N'MALTA', N'MT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (137, N'MARSHALL ISLANDS', N'MH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (138, N'MARTINIQUE', N'MQ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (139, N'MAURITANIA', N'MR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (140, N'MAURITIUS', N'MU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (141, N'MAYOTTE', N'YT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (142, N'MEXICO', N'MX', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (143, N'MICRONESIA, FEDERATED STATES OF', N'FM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (144, N'MOLDOVA, REPUBLIC OF', N'MD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (145, N'MONACO', N'MC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (146, N'MONGOLIA', N'MN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (147, N'MONTSERRAT', N'MS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (148, N'MOROCCO', N'MA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (149, N'MOZAMBIQUE', N'MZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (150, N'MYANMAR', N'MM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (151, N'NAMIBIA', N'NA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (152, N'NAURU', N'NR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (153, N'NEPAL', N'NP', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (154, N'NETHERLANDS', N'NL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (155, N'NETHERLANDS ANTILLES', N'AN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (156, N'NEW CALEDONIA', N'NC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (157, N'NEW ZEALAND', N'NZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (158, N'NICARAGUA', N'NI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (159, N'NIGER', N'NE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (160, N'NIGERIA', N'NG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (161, N'NIUE', N'NU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (162, N'NORFOLK ISLAND', N'NF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (163, N'NORTHERN MARIANA ISLANDS', N'MP', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (164, N'NORWAY', N'NO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (165, N'OMAN', N'OM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (166, N'PAKISTAN', N'PK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (167, N'PALAU', N'PW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (168, N'PALESTINIAN TERRITORY, OCCUPIED', N'PS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (169, N'PANAMA', N'PA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (170, N'PAPUA NEW GUINEA', N'PG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (171, N'PARAGUAY', N'PY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (172, N'PERU', N'PE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (173, N'PHILIPPINES', N'PH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (174, N'PITCAIRN', N'PN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (175, N'POLAND', N'PL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (176, N'PORTUGAL', N'PT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (177, N'PUERTO RICO', N'PR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (178, N'QATAR', N'QA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (179, N'REUNION', N'RE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (180, N'ROMANIA', N'RO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (181, N'RUSSIAN FEDERATION', N'RU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (182, N'RWANDA', N'RW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (183, N'SAINT HELENA', N'SH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (184, N'SAINT KITTS AND NEVIS', N'KN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (185, N'SAINT LUCIA', N'LC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (186, N'SAINT PIERRE AND MIQUELON', N'PM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (187, N'SAINT VINCENT AND THE GRENADINES', N'VC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (188, N'SAMOA', N'WS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (189, N'SAN MARINO', N'SM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (190, N'SAO TOME AND PRINCIPE', N'ST', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (191, N'SAUDI ARABIA', N'SA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (192, N'SENEGAL', N'SN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (193, N'SERBIA AND MONTENEGRO', N'CS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (194, N'SEYCHELLES', N'SC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (195, N'SIERRA LEONE', N'SL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (196, N'SINGAPORE', N'SG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (197, N'SLOVAKIA', N'SK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (198, N'SLOVENIA', N'SI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (199, N'SOLOMON ISLANDS', N'SB', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (200, N'SOMALIA', N'SO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (201, N'SOUTH AFRICA', N'ZA', 1)
GO
print 'Processed 200 total records'
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (202, N'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', N'GS', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (203, N'SPAIN', N'ES', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (204, N'SRI LANKA', N'LK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (205, N'SUDAN', N'SD', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (206, N'SURINAME', N'SR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (207, N'SVALBARD AND JAN MAYEN', N'SJ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (208, N'SWAZILAND', N'SZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (209, N'SWEDEN', N'SE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (210, N'SWITZERLAND', N'CH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (211, N'SYRIAN ARAB REPUBLIC', N'SY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (212, N'TAIWAN, PROVINCE OF CHINA', N'TW', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (213, N'TAJIKISTAN', N'TJ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (214, N'TANZANIA, UNITED REPUBLIC OF', N'TZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (215, N'THAILAND', N'TH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (216, N'TIMOR-LESTE', N'TL', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (217, N'TOGO', N'TG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (218, N'TOKELAU', N'TK', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (219, N'TONGA', N'TO', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (220, N'TRINIDAD AND TOBAGO', N'TT', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (221, N'TUNISIA', N'TN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (222, N'TURKEY', N'TR', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (223, N'TURKMENISTAN', N'TM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (224, N'TURKS AND CAICOS ISLANDS', N'TC', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (225, N'TUVALU', N'TV', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (226, N'UGANDA', N'UG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (227, N'UKRAINE', N'UA', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (228, N'UNITED ARAB EMIRATES', N'AE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (229, N'UNITED KINGDOM', N'GB', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (230, N'UNITED STATES', N'US', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (231, N'UNITED STATES MINOR OUTLYING ISLANDS', N'UM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (232, N'URUGUAY', N'UY', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (233, N'UZBEKISTAN', N'UZ', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (234, N'VANUATU', N'VU', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (235, N'VENEZUELA', N'VE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (236, N'VIET NAM', N'VN', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (237, N'VIRGIN ISLANDS, BRITISH', N'VG', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (238, N'VIRGIN ISLANDS, U.S.', N'VI', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (239, N'WALLIS AND FUTUNA', N'WF', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (240, N'WESTERN SAHARA', N'EH', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (241, N'YEMEN', N'YE', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (242, N'ZAMBIA', N'ZM', 1)
INSERT [Country] ([CountryID], [CountryName], [CountryCode], [Active]) VALUES (243, N'ZIMBABWE', N'ZW', 1)
SET IDENTITY_INSERT [Country] OFF
/****** Object:  Table [dbo].[CustomFieldType]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [CustomFieldType] ON
INSERT [CustomFieldType] ([CustomFieldTypeID], [CustomFieldTypeName], [Active]) VALUES (1, N'TextBox', 1)
INSERT [CustomFieldType] ([CustomFieldTypeID], [CustomFieldTypeName], [Active]) VALUES (2, N'CheckBox', 1)
SET IDENTITY_INSERT [CustomFieldType] OFF
/****** Object:  Table [dbo].[InventoryAction]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [InventoryAction] ON
INSERT [InventoryAction] ([InventoryActionID], [InventoryActionName]) VALUES (1, N'StopSellingOption')
INSERT [InventoryAction] ([InventoryActionID], [InventoryActionName]) VALUES (2, N'StopSellingProduct')
INSERT [InventoryAction] ([InventoryActionID], [InventoryActionName]) VALUES (3, N'ShowPreOrderOption')
INSERT [InventoryAction] ([InventoryActionID], [InventoryActionName]) VALUES (4, N'ShowPreOrderProduct')
INSERT [InventoryAction] ([InventoryActionID], [InventoryActionName]) VALUES (5, N'DoNothing')
SET IDENTITY_INSERT [InventoryAction] OFF
/****** Object:  Table [dbo].[aspnet_SchemaVersions]    Script Date: 06/23/2011 19:22:16 ******/
INSERT [aspnet_SchemaVersions] ([Feature], [CompatibleSchemaVersion], [IsCurrentVersion]) VALUES (N'common', N'1', 1)
INSERT [aspnet_SchemaVersions] ([Feature], [CompatibleSchemaVersion], [IsCurrentVersion]) VALUES (N'health monitoring', N'1', 1)
INSERT [aspnet_SchemaVersions] ([Feature], [CompatibleSchemaVersion], [IsCurrentVersion]) VALUES (N'membership', N'1', 1)
INSERT [aspnet_SchemaVersions] ([Feature], [CompatibleSchemaVersion], [IsCurrentVersion]) VALUES (N'personalization', N'1', 1)
INSERT [aspnet_SchemaVersions] ([Feature], [CompatibleSchemaVersion], [IsCurrentVersion]) VALUES (N'profile', N'1', 1)
INSERT [aspnet_SchemaVersions] ([Feature], [CompatibleSchemaVersion], [IsCurrentVersion]) VALUES (N'role manager', N'1', 1)
/****** Object:  Table [dbo].[aspnet_Applications]    Script Date: 06/23/2011 19:22:16 ******/
INSERT [aspnet_Applications] ([ApplicationName], [LoweredApplicationName], [ApplicationId], [Description]) VALUES (N'InvertedSoftwareCart', N'invertedsoftwarecart', N'de7c5af1-8dcc-4633-921f-8001edca639e', NULL)
/****** Object:  Table [dbo].[OrderStatus]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [OrderStatus] ON
INSERT [OrderStatus] ([OrderStatusID], [OrderStatusName], [Active]) VALUES (1, N'Accepted', 1)
INSERT [OrderStatus] ([OrderStatusID], [OrderStatusName], [Active]) VALUES (2, N'Verifyed', 1)
INSERT [OrderStatus] ([OrderStatusID], [OrderStatusName], [Active]) VALUES (3, N'Shipped', 1)
INSERT [OrderStatus] ([OrderStatusID], [OrderStatusName], [Active]) VALUES (4, N'PaymentError', 1)
SET IDENTITY_INSERT [OrderStatus] OFF
/****** Object:  Table [dbo].[CouponType]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [CouponType] ON
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (1, N'PercentFromProduct', 1)
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (2, N'AmountFromProduct', 1)
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (3, N'PercentFromOrder', 1)
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (4, N'AmountFromOrder', 1)
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (5, N'FreeShippingProduct', 1)
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (6, N'FreeShippingOrder', 1)
INSERT [CouponType] ([CouponTypeID], [CouponTypeName], [Active]) VALUES (7, N'BuyOneGetOneFree', 1)
SET IDENTITY_INSERT [CouponType] OFF
/****** Object:  Table [dbo].[Province]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [Province] ON
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (1, N'Alberta', N'AB', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (2, N'British Columbia', N'BC', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (3, N'Manitoba', N'MB', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (4, N'New Brunswick', N'NB', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (5, N'Newfoundland and Labrador', N'NL', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (6, N'Northwest Territories', N'NT', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (7, N'Nova Scotia', N'NS', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (8, N'Nunavut', N'NU', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (9, N'Ontario', N'ON', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (10, N'Prince Edward Island', N'PE', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (11, N'Quebec', N'QC', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (12, N'Saskatchewan', N'SK', N'1         ')
INSERT [Province] ([ProvinceID], [ProvinceName], [ProvinceCode], [Active]) VALUES (13, N'Yukon', N'YT', N'1         ')
SET IDENTITY_INSERT [Province] OFF
/****** Object:  Table [dbo].[State]    Script Date: 06/23/2011 19:22:16 ******/
SET IDENTITY_INSERT [State] ON
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (1, N'Alabama', N'AL', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (2, N'Alaska', N'AK', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (3, N'American Samoa', N'AS', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (4, N'Arizona', N'AZ', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (5, N'Arkansas', N'AR', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (6, N'California', N'CA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (7, N'Colorado', N'CO', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (8, N'Connecticut', N'CT', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (9, N'Delaware', N'DE', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (10, N'District of Columbia', N'DC', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (11, N'Federated States of Micronesia', N'FM', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (12, N'Florida', N'FL', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (13, N'Georgia', N'GA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (14, N'Guam', N'GU', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (15, N'Hawaii', N'HI', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (16, N'Idaho', N'ID', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (17, N'Illinois', N'IL', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (18, N'Indiana', N'IN', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (19, N'Iowa', N'IA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (20, N'Kansas', N'KS', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (21, N'Kentucky', N'KY', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (22, N'Louisiana', N'LA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (23, N'Maine', N'ME', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (24, N'Marshall Islands', N'MH', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (25, N'Maryland', N'MD', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (26, N'Massachusetts', N'MA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (27, N'Michigan', N'MI', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (28, N'Minnesota', N'MN', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (29, N'Mississippi', N'MS', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (30, N'Missouri', N'MO', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (31, N'Montana', N'MT', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (32, N'Nebraska', N'NE', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (33, N'Nevada', N'NV', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (34, N'New Hampshire', N'NH', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (35, N'New Jersey', N'NJ', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (36, N'New Mexico', N'NM', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (37, N'New York', N'NY', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (38, N'North Carolina', N'NC', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (39, N'North Dakota', N'ND', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (40, N'Northern Mariana Islands', N'MP', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (41, N'Ohio', N'OH', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (42, N'Oklahoma', N'OK', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (43, N'Oregon', N'OR', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (44, N'Palau', N'PW', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (45, N'Pennsylvania', N'PA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (46, N'Puerto Rico', N'PR', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (47, N'Rhode Island', N'RI', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (48, N'South Carolina', N'SC', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (49, N'South Dakota', N'SD', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (50, N'Tennessee', N'TN', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (51, N'Texas', N'TX', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (52, N'Utah', N'UT', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (53, N'Vermont', N'VT', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (54, N'Virgin Islands', N'VI', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (55, N'Virginia', N'VA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (56, N'Washington', N'WA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (57, N'West Virginia', N'WV', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (58, N'Wisconsin', N'WI', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (59, N'Wyoming', N'WY', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (60, N'Armed Forces Americas', N'AA', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (61, N'Armed Forces', N'AE', 1)
INSERT [State] ([StateID], [StateName], [StateCode], [Active]) VALUES (62, N'Armed Forces Pacific', N'AP', 1)
SET IDENTITY_INSERT [State] OFF
/****** Object:  Table [dbo].[Tax]    Script Date: 10/27/2011 09:24:20 ******/
SET IDENTITY_INSERT [dbo].[Tax] ON
INSERT [dbo].[Tax] ([TaxID], [TaxName], [Fixed], [Amount], [IsAfterShipping], [CountryID], [StateID], [ProvinceID], [Active]) VALUES (1, N'CA Sales Tax', 0, CAST(9.000 AS Decimal(18, 3)), 0, 230, 6, NULL, 1)
SET IDENTITY_INSERT [dbo].[Tax] OFF
/****** Object:  Table [dbo].[Product]    Script Date: 10/27/2011 09:33:34 ******/
SET IDENTITY_INSERT [dbo].[Product] ON
INSERT [dbo].[Product] ([ProductID], [ProductName], [CatalogNumber], [Description], [Price], [SalePrice], [Weight], [ShippingWeight], [Height], [ShippingHeight], [Length], [ShippingLength], [Width], [ShippingWidth], [ProductLink], [IsDownloadable], [IsDownloadKeyRequired], [IsDownloadKeyUnique], [DownloadURL], [IsReviewEnabled], [TotalReviewCount], [RatingScore], [Active]) VALUES (1, N'My First Product', N'KGH8765', N'This is my first product', 19.9500, 0.0000, CAST(1 AS Decimal(18, 0)), NULL, CAST(20 AS Decimal(18, 0)), NULL, CAST(40 AS Decimal(18, 0)), NULL, CAST(1 AS Decimal(18, 0)), NULL, NULL, 0, 0, 0, NULL, 1, 0, NULL, 1)
SET IDENTITY_INSERT [dbo].[Product] OFF
/****** Object:  Table [dbo].[Category]    Script Date: 10/27/2011 09:33:34 ******/
SET IDENTITY_INSERT [dbo].[Category] ON
INSERT [dbo].[Category] ([CategoryID], [ParentCategoryID], [CategoryName], [Active]) VALUES (1, NULL, N'My First Category', 1)
SET IDENTITY_INSERT [dbo].[Category] OFF
/****** Object:  Table [dbo].[ProductCategory]    Script Date: 10/27/2011 09:33:34 ******/
SET IDENTITY_INSERT [dbo].[ProductCategory] ON
INSERT [dbo].[ProductCategory] ([ProductCategoryID], [ProductID], [CategoryID], [Active]) VALUES (1, 1, 1, 1)
SET IDENTITY_INSERT [dbo].[ProductCategory] OFF
/****** Object:  Table [dbo].[ShippingProvider]    Script Date: 10/27/2011 09:33:34 ******/
SET IDENTITY_INSERT [dbo].[ShippingProvider] ON
INSERT [dbo].[ShippingProvider] ([ShippingProviderID], [ShippingProviderName], [ShippingCost], [Active]) VALUES (1, N'UPS', 19.9500, 1)
INSERT [dbo].[ShippingProvider] ([ShippingProviderID], [ShippingProviderName], [ShippingCost], [Active]) VALUES (2, N'USPS Ground', 12.9500, 1)
SET IDENTITY_INSERT [dbo].[ShippingProvider] OFF