//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_FeaturedProduct_Category", "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Category), "FeaturedProduct", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.FeaturedProduct))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_ProductCategory_Category", "Category", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Category), "ProductCategory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.ProductCategory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_FeaturedProduct_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "FeaturedProduct", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.FeaturedProduct))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_Image_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "Image", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Image))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_ProductCategory_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "ProductCategory", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.ProductCategory))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_RelatedProduct_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "RelatedProduct", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.RelatedProduct))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_RelatedProduct_Product1", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "RelatedProduct", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.RelatedProduct))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_ProductOption_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "ProductOption", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.ProductOption))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_CustomField_CustomFieldType", "CustomFieldType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.CustomFieldType), "CustomField", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.CustomField))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("InvertedSoftwareCartModel", "FK_CustomField_Product", "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.Product), "CustomField", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvertedSoftware.ShoppingCart.DataLayer.Entities.CustomField))]

// Original file name:
// Generation date: 5/9/2009 6:53:57 PM
namespace InvertedSoftware.ShoppingCart.DataLayer.Entities
{
    
    /// <summary>
    /// There are no comments for Entities in the schema.
    /// </summary>
    public partial class Entities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : 
                base("name=Entities", "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : 
                base(connectionString, "Entities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Entities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Category> Category
        {
            get
            {
                if ((this._Category == null))
                {
                    this._Category = base.CreateQuery<Category>("[Category]");
                }
                return this._Category;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Category> _Category;
        /// <summary>
        /// There are no comments for FeaturedProduct in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FeaturedProduct> FeaturedProduct
        {
            get
            {
                if ((this._FeaturedProduct == null))
                {
                    this._FeaturedProduct = base.CreateQuery<FeaturedProduct>("[FeaturedProduct]");
                }
                return this._FeaturedProduct;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FeaturedProduct> _FeaturedProduct;
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Image> Image
        {
            get
            {
                if ((this._Image == null))
                {
                    this._Image = base.CreateQuery<Image>("[Image]");
                }
                return this._Image;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Image> _Image;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Product> Product
        {
            get
            {
                if ((this._Product == null))
                {
                    this._Product = base.CreateQuery<Product>("[Product]");
                }
                return this._Product;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Product> _Product;
        /// <summary>
        /// There are no comments for ProductCategory in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductCategory> ProductCategory
        {
            get
            {
                if ((this._ProductCategory == null))
                {
                    this._ProductCategory = base.CreateQuery<ProductCategory>("[ProductCategory]");
                }
                return this._ProductCategory;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductCategory> _ProductCategory;
        /// <summary>
        /// There are no comments for RelatedProduct in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<RelatedProduct> RelatedProduct
        {
            get
            {
                if ((this._RelatedProduct == null))
                {
                    this._RelatedProduct = base.CreateQuery<RelatedProduct>("[RelatedProduct]");
                }
                return this._RelatedProduct;
            }
        }
        private global::System.Data.Objects.ObjectQuery<RelatedProduct> _RelatedProduct;
        /// <summary>
        /// There are no comments for ProductOption in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductOption> ProductOption
        {
            get
            {
                if ((this._ProductOption == null))
                {
                    this._ProductOption = base.CreateQuery<ProductOption>("[ProductOption]");
                }
                return this._ProductOption;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductOption> _ProductOption;
        /// <summary>
        /// There are no comments for CustomField in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CustomField> CustomField
        {
            get
            {
                if ((this._CustomField == null))
                {
                    this._CustomField = base.CreateQuery<CustomField>("[CustomField]");
                }
                return this._CustomField;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CustomField> _CustomField;
        /// <summary>
        /// There are no comments for CustomFieldType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CustomFieldType> CustomFieldType
        {
            get
            {
                if ((this._CustomFieldType == null))
                {
                    this._CustomFieldType = base.CreateQuery<CustomFieldType>("[CustomFieldType]");
                }
                return this._CustomFieldType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CustomFieldType> _CustomFieldType;
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
        /// <summary>
        /// There are no comments for FeaturedProduct in the schema.
        /// </summary>
        public void AddToFeaturedProduct(FeaturedProduct featuredProduct)
        {
            base.AddObject("FeaturedProduct", featuredProduct);
        }
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        public void AddToImage(Image image)
        {
            base.AddObject("Image", image);
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public void AddToProduct(Product product)
        {
            base.AddObject("Product", product);
        }
        /// <summary>
        /// There are no comments for ProductCategory in the schema.
        /// </summary>
        public void AddToProductCategory(ProductCategory productCategory)
        {
            base.AddObject("ProductCategory", productCategory);
        }
        /// <summary>
        /// There are no comments for RelatedProduct in the schema.
        /// </summary>
        public void AddToRelatedProduct(RelatedProduct relatedProduct)
        {
            base.AddObject("RelatedProduct", relatedProduct);
        }
        /// <summary>
        /// There are no comments for ProductOption in the schema.
        /// </summary>
        public void AddToProductOption(ProductOption productOption)
        {
            base.AddObject("ProductOption", productOption);
        }
        /// <summary>
        /// There are no comments for CustomField in the schema.
        /// </summary>
        public void AddToCustomField(CustomField customField)
        {
            base.AddObject("CustomField", customField);
        }
        /// <summary>
        /// There are no comments for CustomFieldType in the schema.
        /// </summary>
        public void AddToCustomFieldType(CustomFieldType customFieldType)
        {
            base.AddObject("CustomFieldType", customFieldType);
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.Category in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="Category")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Category : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryID">Initial value of CategoryID.</param>
        /// <param name="categoryName">Initial value of CategoryName.</param>
        /// <param name="active">Initial value of Active.</param>
        public static Category CreateCategory(int categoryID, string categoryName, bool active)
        {
            Category category = new Category();
            category.CategoryID = categoryID;
            category.CategoryName = categoryName;
            category.Active = active;
            return category;
        }
        /// <summary>
        /// There are no comments for Property CategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this._CategoryID;
            }
            set
            {
                this.OnCategoryIDChanging(value);
                this.ReportPropertyChanging("CategoryID");
                this._CategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CategoryID");
                this.OnCategoryIDChanged();
            }
        }
        private int _CategoryID;
        partial void OnCategoryIDChanging(int value);
        partial void OnCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property ParentCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentCategoryID
        {
            get
            {
                return this._ParentCategoryID;
            }
            set
            {
                this.OnParentCategoryIDChanging(value);
                this.ReportPropertyChanging("ParentCategoryID");
                this._ParentCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentCategoryID");
                this.OnParentCategoryIDChanged();
            }
        }
        private global::System.Nullable<int> _ParentCategoryID;
        partial void OnParentCategoryIDChanging(global::System.Nullable<int> value);
        partial void OnParentCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property CategoryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this._CategoryName;
            }
            set
            {
                this.OnCategoryNameChanging(value);
                this.ReportPropertyChanging("CategoryName");
                this._CategoryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CategoryName");
                this.OnCategoryNameChanged();
            }
        }
        private string _CategoryName;
        partial void OnCategoryNameChanging(string value);
        partial void OnCategoryNameChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for FeaturedProduct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_FeaturedProduct_Category", "FeaturedProduct")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<FeaturedProduct> FeaturedProduct
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<FeaturedProduct>("InvertedSoftwareCartModel.FK_FeaturedProduct_Category", "FeaturedProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<FeaturedProduct>("InvertedSoftwareCartModel.FK_FeaturedProduct_Category", "FeaturedProduct", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProductCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_ProductCategory_Category", "ProductCategory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProductCategory> ProductCategory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProductCategory>("InvertedSoftwareCartModel.FK_ProductCategory_Category", "ProductCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProductCategory>("InvertedSoftwareCartModel.FK_ProductCategory_Category", "ProductCategory", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.FeaturedProduct in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FeaturedProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="FeaturedProduct")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FeaturedProduct : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FeaturedProduct object.
        /// </summary>
        /// <param name="featuredProductID">Initial value of FeaturedProductID.</param>
        /// <param name="active">Initial value of Active.</param>
        public static FeaturedProduct CreateFeaturedProduct(int featuredProductID, bool active)
        {
            FeaturedProduct featuredProduct = new FeaturedProduct();
            featuredProduct.FeaturedProductID = featuredProductID;
            featuredProduct.Active = active;
            return featuredProduct;
        }
        /// <summary>
        /// There are no comments for Property FeaturedProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int FeaturedProductID
        {
            get
            {
                return this._FeaturedProductID;
            }
            set
            {
                this.OnFeaturedProductIDChanging(value);
                this.ReportPropertyChanging("FeaturedProductID");
                this._FeaturedProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FeaturedProductID");
                this.OnFeaturedProductIDChanged();
            }
        }
        private int _FeaturedProductID;
        partial void OnFeaturedProductIDChanging(int value);
        partial void OnFeaturedProductIDChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_FeaturedProduct_Category", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("InvertedSoftwareCartModel.FK_FeaturedProduct_Category", "Category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("InvertedSoftwareCartModel.FK_FeaturedProduct_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("InvertedSoftwareCartModel.FK_FeaturedProduct_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("InvertedSoftwareCartModel.FK_FeaturedProduct_Category", "Category", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_FeaturedProduct_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_FeaturedProduct_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_FeaturedProduct_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_FeaturedProduct_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_FeaturedProduct_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.Image in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ImageID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="Image")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Image : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="imageID">Initial value of ImageID.</param>
        /// <param name="imageURL">Initial value of ImageURL.</param>
        /// <param name="active">Initial value of Active.</param>
        public static Image CreateImage(int imageID, string imageURL, bool active)
        {
            Image image = new Image();
            image.ImageID = imageID;
            image.ImageURL = imageURL;
            image.Active = active;
            return image;
        }
        /// <summary>
        /// There are no comments for Property ImageID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ImageID
        {
            get
            {
                return this._ImageID;
            }
            set
            {
                this.OnImageIDChanging(value);
                this.ReportPropertyChanging("ImageID");
                this._ImageID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ImageID");
                this.OnImageIDChanged();
            }
        }
        private int _ImageID;
        partial void OnImageIDChanging(int value);
        partial void OnImageIDChanged();
        /// <summary>
        /// There are no comments for Property ParentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentID
        {
            get
            {
                return this._ParentID;
            }
            set
            {
                this.OnParentIDChanging(value);
                this.ReportPropertyChanging("ParentID");
                this._ParentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentID");
                this.OnParentIDChanged();
            }
        }
        private global::System.Nullable<int> _ParentID;
        partial void OnParentIDChanging(global::System.Nullable<int> value);
        partial void OnParentIDChanged();
        /// <summary>
        /// There are no comments for Property SortOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SortOrder
        {
            get
            {
                return this._SortOrder;
            }
            set
            {
                this.OnSortOrderChanging(value);
                this.ReportPropertyChanging("SortOrder");
                this._SortOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SortOrder");
                this.OnSortOrderChanged();
            }
        }
        private global::System.Nullable<int> _SortOrder;
        partial void OnSortOrderChanging(global::System.Nullable<int> value);
        partial void OnSortOrderChanged();
        /// <summary>
        /// There are no comments for Property ImageName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName
        {
            get
            {
                return this._ImageName;
            }
            set
            {
                this.OnImageNameChanging(value);
                this.ReportPropertyChanging("ImageName");
                this._ImageName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ImageName");
                this.OnImageNameChanged();
            }
        }
        private string _ImageName;
        partial void OnImageNameChanging(string value);
        partial void OnImageNameChanged();
        /// <summary>
        /// There are no comments for Property ImageURL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL
        {
            get
            {
                return this._ImageURL;
            }
            set
            {
                this.OnImageURLChanging(value);
                this.ReportPropertyChanging("ImageURL");
                this._ImageURL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ImageURL");
                this.OnImageURLChanged();
            }
        }
        private string _ImageURL;
        partial void OnImageURLChanging(string value);
        partial void OnImageURLChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_Image_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_Image_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_Image_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_Image_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_Image_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="Product")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Product : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="active">Initial value of Active.</param>
        public static Product CreateProduct(int productID, bool active)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.Active = active;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this.ReportPropertyChanging("ProductName");
                this._ProductName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ProductName");
                this.OnProductNameChanged();
            }
        }
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property CatalogNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CatalogNumber
        {
            get
            {
                return this._CatalogNumber;
            }
            set
            {
                this.OnCatalogNumberChanging(value);
                this.ReportPropertyChanging("CatalogNumber");
                this._CatalogNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CatalogNumber");
                this.OnCatalogNumberChanged();
            }
        }
        private string _CatalogNumber;
        partial void OnCatalogNumberChanging(string value);
        partial void OnCatalogNumberChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> price
        {
            get
            {
                return this._price;
            }
            set
            {
                this.OnpriceChanging(value);
                this.ReportPropertyChanging("price");
                this._price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("price");
                this.OnpriceChanged();
            }
        }
        private global::System.Nullable<decimal> _price;
        partial void OnpriceChanging(global::System.Nullable<decimal> value);
        partial void OnpriceChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for FeaturedProduct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_FeaturedProduct_Product", "FeaturedProduct")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<FeaturedProduct> FeaturedProduct
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<FeaturedProduct>("InvertedSoftwareCartModel.FK_FeaturedProduct_Product", "FeaturedProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<FeaturedProduct>("InvertedSoftwareCartModel.FK_FeaturedProduct_Product", "FeaturedProduct", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Image in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_Image_Product", "Image")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Image> Image
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Image>("InvertedSoftwareCartModel.FK_Image_Product", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Image>("InvertedSoftwareCartModel.FK_Image_Product", "Image", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProductCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_ProductCategory_Product", "ProductCategory")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProductCategory> ProductCategory
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProductCategory>("InvertedSoftwareCartModel.FK_ProductCategory_Product", "ProductCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProductCategory>("InvertedSoftwareCartModel.FK_ProductCategory_Product", "ProductCategory", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for RelatedProduct in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_RelatedProduct_Product", "RelatedProduct")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<RelatedProduct> RelatedProduct
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<RelatedProduct>("InvertedSoftwareCartModel.FK_RelatedProduct_Product", "RelatedProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<RelatedProduct>("InvertedSoftwareCartModel.FK_RelatedProduct_Product", "RelatedProduct", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for RelatedProduct1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_RelatedProduct_Product1", "RelatedProduct")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<RelatedProduct> RelatedProduct1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<RelatedProduct>("InvertedSoftwareCartModel.FK_RelatedProduct_Product1", "RelatedProduct");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<RelatedProduct>("InvertedSoftwareCartModel.FK_RelatedProduct_Product1", "RelatedProduct", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProductOption in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_ProductOption_Product", "ProductOption")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProductOption> ProductOption
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProductOption>("InvertedSoftwareCartModel.FK_ProductOption_Product", "ProductOption");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProductOption>("InvertedSoftwareCartModel.FK_ProductOption_Product", "ProductOption", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CustomField in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_CustomField_Product", "CustomField")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CustomField> CustomField
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CustomField>("InvertedSoftwareCartModel.FK_CustomField_Product", "CustomField");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CustomField>("InvertedSoftwareCartModel.FK_CustomField_Product", "CustomField", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.ProductCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductCategoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="ProductCategory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductCategory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProductCategory object.
        /// </summary>
        /// <param name="productCategoryID">Initial value of ProductCategoryID.</param>
        /// <param name="active">Initial value of Active.</param>
        public static ProductCategory CreateProductCategory(int productCategoryID, bool active)
        {
            ProductCategory productCategory = new ProductCategory();
            productCategory.ProductCategoryID = productCategoryID;
            productCategory.Active = active;
            return productCategory;
        }
        /// <summary>
        /// There are no comments for Property ProductCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryID
        {
            get
            {
                return this._ProductCategoryID;
            }
            set
            {
                this.OnProductCategoryIDChanging(value);
                this.ReportPropertyChanging("ProductCategoryID");
                this._ProductCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductCategoryID");
                this.OnProductCategoryIDChanged();
            }
        }
        private int _ProductCategoryID;
        partial void OnProductCategoryIDChanging(int value);
        partial void OnProductCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_ProductCategory_Category", "Category")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Category Category
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("InvertedSoftwareCartModel.FK_ProductCategory_Category", "Category").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("InvertedSoftwareCartModel.FK_ProductCategory_Category", "Category").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Category in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Category> CategoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Category>("InvertedSoftwareCartModel.FK_ProductCategory_Category", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Category>("InvertedSoftwareCartModel.FK_ProductCategory_Category", "Category", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_ProductCategory_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductCategory_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductCategory_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductCategory_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductCategory_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.RelatedProduct in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RelatedProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="RelatedProduct")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RelatedProduct : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new RelatedProduct object.
        /// </summary>
        /// <param name="relatedProductID">Initial value of RelatedProductID.</param>
        public static RelatedProduct CreateRelatedProduct(int relatedProductID)
        {
            RelatedProduct relatedProduct = new RelatedProduct();
            relatedProduct.RelatedProductID = relatedProductID;
            return relatedProduct;
        }
        /// <summary>
        /// There are no comments for Property RelatedProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int RelatedProductID
        {
            get
            {
                return this._RelatedProductID;
            }
            set
            {
                this.OnRelatedProductIDChanging(value);
                this.ReportPropertyChanging("RelatedProductID");
                this._RelatedProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RelatedProductID");
                this.OnRelatedProductIDChanged();
            }
        }
        private int _RelatedProductID;
        partial void OnRelatedProductIDChanging(int value);
        partial void OnRelatedProductIDChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private global::System.Nullable<bool> _Active;
        partial void OnActiveChanging(global::System.Nullable<bool> value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_RelatedProduct_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product", "Product", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Product1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_RelatedProduct_Product1", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product1", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product1", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product1 in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> Product1Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product1", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_RelatedProduct_Product1", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.ProductOption in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductOptionID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="ProductOption")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductOption : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProductOption object.
        /// </summary>
        /// <param name="productOptionID">Initial value of ProductOptionID.</param>
        /// <param name="productOptionName">Initial value of ProductOptionName.</param>
        /// <param name="productOptionGroup">Initial value of ProductOptionGroup.</param>
        /// <param name="priceChange">Initial value of PriceChange.</param>
        /// <param name="active">Initial value of Active.</param>
        public static ProductOption CreateProductOption(int productOptionID, string productOptionName, string productOptionGroup, decimal priceChange, bool active)
        {
            ProductOption productOption = new ProductOption();
            productOption.ProductOptionID = productOptionID;
            productOption.ProductOptionName = productOptionName;
            productOption.ProductOptionGroup = productOptionGroup;
            productOption.PriceChange = priceChange;
            productOption.Active = active;
            return productOption;
        }
        /// <summary>
        /// There are no comments for Property ProductOptionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductOptionID
        {
            get
            {
                return this._ProductOptionID;
            }
            set
            {
                this.OnProductOptionIDChanging(value);
                this.ReportPropertyChanging("ProductOptionID");
                this._ProductOptionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductOptionID");
                this.OnProductOptionIDChanged();
            }
        }
        private int _ProductOptionID;
        partial void OnProductOptionIDChanging(int value);
        partial void OnProductOptionIDChanged();
        /// <summary>
        /// There are no comments for Property ProductOptionName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductOptionName
        {
            get
            {
                return this._ProductOptionName;
            }
            set
            {
                this.OnProductOptionNameChanging(value);
                this.ReportPropertyChanging("ProductOptionName");
                this._ProductOptionName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductOptionName");
                this.OnProductOptionNameChanged();
            }
        }
        private string _ProductOptionName;
        partial void OnProductOptionNameChanging(string value);
        partial void OnProductOptionNameChanged();
        /// <summary>
        /// There are no comments for Property ProductOptionGroup in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductOptionGroup
        {
            get
            {
                return this._ProductOptionGroup;
            }
            set
            {
                this.OnProductOptionGroupChanging(value);
                this.ReportPropertyChanging("ProductOptionGroup");
                this._ProductOptionGroup = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductOptionGroup");
                this.OnProductOptionGroupChanged();
            }
        }
        private string _ProductOptionGroup;
        partial void OnProductOptionGroupChanging(string value);
        partial void OnProductOptionGroupChanged();
        /// <summary>
        /// There are no comments for Property PriceChange in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceChange
        {
            get
            {
                return this._PriceChange;
            }
            set
            {
                this.OnPriceChangeChanging(value);
                this.ReportPropertyChanging("PriceChange");
                this._PriceChange = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PriceChange");
                this.OnPriceChangeChanged();
            }
        }
        private decimal _PriceChange;
        partial void OnPriceChangeChanging(decimal value);
        partial void OnPriceChangeChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_ProductOption_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductOption_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductOption_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductOption_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_ProductOption_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.CustomField in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomFieldID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="CustomField")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CustomField : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CustomField object.
        /// </summary>
        /// <param name="customFieldID">Initial value of CustomFieldID.</param>
        /// <param name="customFieldName">Initial value of CustomFieldName.</param>
        /// <param name="isRequired">Initial value of IsRequired.</param>
        /// <param name="active">Initial value of Active.</param>
        public static CustomField CreateCustomField(int customFieldID, string customFieldName, bool isRequired, bool active)
        {
            CustomField customField = new CustomField();
            customField.CustomFieldID = customFieldID;
            customField.CustomFieldName = customFieldName;
            customField.IsRequired = isRequired;
            customField.Active = active;
            return customField;
        }
        /// <summary>
        /// There are no comments for Property CustomFieldID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomFieldID
        {
            get
            {
                return this._CustomFieldID;
            }
            set
            {
                this.OnCustomFieldIDChanging(value);
                this.ReportPropertyChanging("CustomFieldID");
                this._CustomFieldID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomFieldID");
                this.OnCustomFieldIDChanged();
            }
        }
        private int _CustomFieldID;
        partial void OnCustomFieldIDChanging(int value);
        partial void OnCustomFieldIDChanged();
        /// <summary>
        /// There are no comments for Property CustomFieldName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomFieldName
        {
            get
            {
                return this._CustomFieldName;
            }
            set
            {
                this.OnCustomFieldNameChanging(value);
                this.ReportPropertyChanging("CustomFieldName");
                this._CustomFieldName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CustomFieldName");
                this.OnCustomFieldNameChanged();
            }
        }
        private string _CustomFieldName;
        partial void OnCustomFieldNameChanging(string value);
        partial void OnCustomFieldNameChanged();
        /// <summary>
        /// There are no comments for Property IsRequired in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRequired
        {
            get
            {
                return this._IsRequired;
            }
            set
            {
                this.OnIsRequiredChanging(value);
                this.ReportPropertyChanging("IsRequired");
                this._IsRequired = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsRequired");
                this.OnIsRequiredChanged();
            }
        }
        private bool _IsRequired;
        partial void OnIsRequiredChanging(bool value);
        partial void OnIsRequiredChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for CustomFieldType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_CustomField_CustomFieldType", "CustomFieldType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CustomFieldType CustomFieldType
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CustomFieldType>("InvertedSoftwareCartModel.FK_CustomField_CustomFieldType", "CustomFieldType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CustomFieldType>("InvertedSoftwareCartModel.FK_CustomField_CustomFieldType", "CustomFieldType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CustomFieldType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CustomFieldType> CustomFieldTypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CustomFieldType>("InvertedSoftwareCartModel.FK_CustomField_CustomFieldType", "CustomFieldType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CustomFieldType>("InvertedSoftwareCartModel.FK_CustomField_CustomFieldType", "CustomFieldType", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_CustomField_Product", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Product Product
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_CustomField_Product", "Product").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_CustomField_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Product> ProductReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Product>("InvertedSoftwareCartModel.FK_CustomField_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Product>("InvertedSoftwareCartModel.FK_CustomField_Product", "Product", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for InvertedSoftwareCartModel.CustomFieldType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CustomFieldTypeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="InvertedSoftwareCartModel", Name="CustomFieldType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CustomFieldType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CustomFieldType object.
        /// </summary>
        /// <param name="customFieldTypeID">Initial value of CustomFieldTypeID.</param>
        /// <param name="active">Initial value of Active.</param>
        public static CustomFieldType CreateCustomFieldType(int customFieldTypeID, bool active)
        {
            CustomFieldType customFieldType = new CustomFieldType();
            customFieldType.CustomFieldTypeID = customFieldTypeID;
            customFieldType.Active = active;
            return customFieldType;
        }
        /// <summary>
        /// There are no comments for Property CustomFieldTypeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomFieldTypeID
        {
            get
            {
                return this._CustomFieldTypeID;
            }
            set
            {
                this.OnCustomFieldTypeIDChanging(value);
                this.ReportPropertyChanging("CustomFieldTypeID");
                this._CustomFieldTypeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CustomFieldTypeID");
                this.OnCustomFieldTypeIDChanged();
            }
        }
        private int _CustomFieldTypeID;
        partial void OnCustomFieldTypeIDChanging(int value);
        partial void OnCustomFieldTypeIDChanged();
        /// <summary>
        /// There are no comments for Property CustomFieldTypeName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomFieldTypeName
        {
            get
            {
                return this._CustomFieldTypeName;
            }
            set
            {
                this.OnCustomFieldTypeNameChanging(value);
                this.ReportPropertyChanging("CustomFieldTypeName");
                this._CustomFieldTypeName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CustomFieldTypeName");
                this.OnCustomFieldTypeNameChanged();
            }
        }
        private string _CustomFieldTypeName;
        partial void OnCustomFieldTypeNameChanging(string value);
        partial void OnCustomFieldTypeNameChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this.ReportPropertyChanging("Active");
                this._Active = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Active");
                this.OnActiveChanged();
            }
        }
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for CustomField in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InvertedSoftwareCartModel", "FK_CustomField_CustomFieldType", "CustomField")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CustomField> CustomField
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CustomField>("InvertedSoftwareCartModel.FK_CustomField_CustomFieldType", "CustomField");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CustomField>("InvertedSoftwareCartModel.FK_CustomField_CustomFieldType", "CustomField", value);
                }
            }
        }
    }
}
